### ISSUE TITLE
Unable to build on Ubuntu 20.04

### ISSUE THREAD

**Issue by stanleyk** [MaxChinni/ike-for-ubuntu#2]
Hi, thanks for this repository. I am currently unable to build it on Ubuntu 20.04 - possibly an openssl version issue. Do you have any idea how to solve this? Thanks!

```
/usr/local/src/ike/source/libike/manager.file.cpp: In member function ‘bool _CONFIG_MANAGER::file_pcf_load(CONFIG&, const char*, bool&)’:
/usr/local/src/ike/source/libike/manager.file.cpp:682:19: error: aggregate ‘EVP_CIPHER_CTX ctx_cipher’ has incomplete type and cannot be defined
  682 |    EVP_CIPHER_CTX ctx_cipher;
      |                   ^~~~~~~~~~
make[2]: *** [source/libike/CMakeFiles/ss_ike.dir/build.make:102: source/libike/CMakeFiles/ss_ike.dir/manager.file.o] Chyba 1
make[1]: *** [CMakeFiles/Makefile2:333: source/libike/CMakeFiles/ss_ike.dir/all] Chyba 2
make: *** [Makefile:130: all] Chyba 2
root@koza:/usr/local/src/ike# make install
[  3%] Built target ss_ith
[  6%] Built target ss_log
[ 10%] Built target ss_idb
[ 14%] Built target ss_pfk
[ 15%] Building CXX object source/libike/CMakeFiles/ss_ike.dir/manager.file.o

```

**Comment by bollmichael** [comment]
Hey @stanleyk,

late but maybe you still need/want it:

looks like your patch did not apply. In my case i did not have the "dos2unix" installed. 

sudo apt install dos2unix

the conversion of the linebreaks did not work and then the patch won't apply. Just start from beginning of the instructions after installing dos2unix.

Greetings,

Michael

**Comment by MaxChinni** [comment]
Thank you, I updated the instructions.
